// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4fPSwB3h5miXY42Wap3Kgg-ZUhpiub6k',
    appId: '1:695039205705:web:39f57b9b13487f03d6fa98',
    messagingSenderId: '695039205705',
    projectId: 'douddy-app',
    authDomain: 'douddy-app.firebaseapp.com',
    storageBucket: 'douddy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDwbAgJ55wZVhcKOph2WzztYm_c0YPVw',
    appId: '1:695039205705:android:89c743b03ae36d5cd6fa98',
    messagingSenderId: '695039205705',
    projectId: 'douddy-app',
    storageBucket: 'douddy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ZXmG_FYXJyPYnMMCm2um_PyBmvNw_dY',
    appId: '1:695039205705:ios:1261d0fe89c1d187d6fa98',
    messagingSenderId: '695039205705',
    projectId: 'douddy-app',
    storageBucket: 'douddy-app.firebasestorage.app',
    iosBundleId: 'com.example.douddyv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ZXmG_FYXJyPYnMMCm2um_PyBmvNw_dY',
    appId: '1:695039205705:ios:1261d0fe89c1d187d6fa98',
    messagingSenderId: '695039205705',
    projectId: 'douddy-app',
    storageBucket: 'douddy-app.firebasestorage.app',
    iosBundleId: 'com.example.douddyv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4fPSwB3h5miXY42Wap3Kgg-ZUhpiub6k',
    appId: '1:695039205705:web:ff7d13caf4b61309d6fa98',
    messagingSenderId: '695039205705',
    projectId: 'douddy-app',
    authDomain: 'douddy-app.firebaseapp.com',
    storageBucket: 'douddy-app.firebasestorage.app',
  );
}
